### ISSUE TITLE
Handle page size errors

### ISSUE THREAD

**Issue by Daniel-Mietchen** [guyfawcus/PagesBot#4]
Example from https://www.wikidata.org/wiki/Q22676705 : 

![image](https://user-images.githubusercontent.com/465923/203339814-06272b13-0057-483a-a61f-ebfa1b0d2821.png)

For more test cases, see https://www.wikidata.org/wiki/Special:LongPages .

**Comment by guyfawcus** [comment]
That's a lot of authors! I've seen a few items before like this for papers from CERN and other big organisations, but hadn't found any that were too big to save changes. It's an interesting limitation; thanks for the heads-up.
